# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        python -m pytest tests/ --self-contained-html
    - uses: actions/upload-artifact@v4
      with:
        name: reports
        if-no-files-found: warn
        path: |
          reports/report*.html
    - uses: actions/upload-artifact@v4
      with:
        name: logs
        if-no-files-found: warn
        path: |
          logs/*.log
    - uses: actions/upload-artifact@v4
      with:
        name: screenshots
        if-no-files-found: warn
        path: |
          screenshots/*.png